routes/web.php
<?php

use App\Http\Controllers\Admin\AddPermissionsController;
use App\Http\Controllers\Admin\AddPlasmaDonerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('pages.dashboard');
});

Auth::routes(['verify' => true]);

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'Admin\DashboardController@index')->name('home');

//Plasma
Route::get('plasma-verify/{plasma}', 'Admin\AddPlasmaDonerController@verify')->name('plasma.verify');
Route::resource('plasma', 'Admin\AddPlasmaDonerController');

Route::get('blood-verify/{bloodDonar}', 'Admin\AddBloodController@verify')->name('blood.verify');
Route::resource('blood', 'Admin\AddBloodController');

Route::get('ambulance-services-verify/{ambulance_service}', 'Admin\AddAmbulanceServicesController@verify')->name('ambulance-services.verify');
Route::resource('ambulance-services', 'Admin\AddAmbulanceServicesController');

//Har Oxygen
Route::get('oxygen-verify/{oxygen}', 'Admin\AddOxygenController@verify')->name('oxygen.verify');
Route::resource('oxygen', 'Admin\AddOxygenController');

Route::middleware(['auth','role:super-admin'])->group(function () {
    Route::resource('permissions', 'Admin\AddPermissionsController');
    Route::resource('roles', 'Admin\AddRolesController');
});

Route::middleware(['auth'])->group(function () {
    Route::get('profile', 'Admin\UserController@profile')->name('profile');
    Route::get('edit-profile', 'Admin\UserController@editProfile')->name('edit.profile');
    Route::post('edit-profile', 'Admin\UserController@update')->name('update.profile');
});

// Requests
Route::resource('requests', 'Admin\RequestsController');

app/Http/Livewire/Dashboards/Roles.php
<?php

namespace App\Http\Livewire\Dashboards;

use Livewire\Component;
use Livewire\WithPagination;
use Maklad\Permission\Models\Role;

class Roles extends Component
{
    use WithPagination;

    public $month = '';
    protected $sales;
    public $perPage = 10;
    public $sortField;
    public $sortAsc = false;
    public $search = null;

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $search = $this->search;
        $sortField = $this->sortField?$this->sortField:'id';
        return view('livewire.dashboards.roles', [
            'roles' => Role::when($search, function ($query) use ($search) {
                return $query->where(function ($query2) use ($search) {
                        $query2->where('name', 'LIKE', "%$search%")
                            ->orWhere('guard_name', 'LIKE', "%$search%");
                });
            })
            ->orderBy($sortField, $this->sortAsc ? 'asc' : 'desc')
            ->paginate(10),
        ]);
    }

    // public function render()
    // {
    //     return view('livewire.dashboards.roles');
    // }
}

resources/views/dashoard/roles/add.blade.php
@extends('layouts.main')

@section('title', 'Roles')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card mb-4">
          <div class="card-header pb-0">
            <h6>Permission</h6>
          </div>
          <div class="card-body px-4 pt-2 pb-2">
            <form action="{{route('roles.store')}}" method="POST">
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="name">Role</label>
                      <input type="text" class="form-control @error('name') is-invalid @enderror"  name="name" placeholder="Permission">
                      @error('name')
                      <small class="alert-text text-danger">{{ $message }}</small>
                      @enderror
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="lastt_name">Guard</label>
                      {{-- <input type="text" placeholder="Your Guard Name" class="form-control @error('guard_name') is-invalid @enderror" id="guard_name" name="guard_name"/> --}}
                      <select class="form-control @error('guard_name') is-invalid @enderror" name="guard_name" id="exampleFormControlSelect1">
                        <option value="">Select a Guard</option>
                        <option>web</option>
                        <option>api</option>
                    </select>
                      @error('guard_name')
                      <small class="alert-text text-danger">{{ $message }}</small>
                      @enderror
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-10">
                    <label for="lastt_name">Permissions </label>
                    @foreach ($premissions as $premission)
                      <div class="form-check form-check">
                        <input class="form-check-input" type="checkbox" name="permission[]" id="inlineCheckbox1" value="{{$premission->name}}">
                        <label class="form-check-label" for="inlineCheckbox1">{{$premission->name}}</label>
                      </div>
                    @endforeach
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-12">
                    <div class="text-center">
                        @csrf
                        <a href="{{route('roles.index')}}" class="btn btn-outline-secondary w-10 mt-4 mb-5 px-3">Go Back</a>
                        <button type="submit" class="btn bg-gradient-info w-20 mt-4 mb-5">Submit</button>
                    </div>
                  </div>
                </div>
                {{-- <div class="row"> --}}
            </form>
          </div>
        </div>
      </div>
</div>

@endsection

resources/views/dashoard/roles/edit.blade.php
@extends('layouts.main')

@section('title', 'Roles')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card mb-4">
          <div class="card-header pb-0">
            <h6>Permission</h6>
          </div>
          <div class="card-body px-4 pt-2 pb-2">
            <form action="{{route('roles.update',$role->id)}}" method="POST">
                @method('PUT')
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="name">Role</label>
                      <input type="text" class="form-control @error('name') is-invalid @enderror" value="{{$role->name}}" name="name" placeholder="Permission">
                      @error('name')
                      <small class="alert-text text-danger">{{ $message }}</small>
                      @enderror
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="lastt_name">Guard</label>
                      {{-- <input type="text" placeholder="Your Guard Name" class="form-control @error('guard_name') is-invalid @enderror" id="guard_name" name="guard_name"/> --}}
                      <select class="form-control @error('guard_name') is-invalid @enderror" name="guard_name" id="exampleFormControlSelect1">
                        <option value="">Select a Guard</option>
                        <option {{$role->guard_name=='web'?"selected":''}}>web</option>
                        <option {{$role->guard_name=='api'?"selected":''}}>api</option>
                    </select>
                      @error('guard_name')
                      <small class="alert-text text-danger">{{ $message }}</small>
                      @enderror
                    </div>
                  </div>
                </div>
                {{-- {{dd($role->permission_ids)}} --}}

                <div class="row">
                  <div class="col-md-10">
                    <label for="lastt_name">Permissions </label>
                    @foreach ($premissions as $premission)
                      <div class="form-check form-check">
                        <input {{in_array($premission->id,$role->permission_ids)?"checked":""}} class="form-check-input" type="checkbox" name="permission[]" id="inlineCheckbox1" value="{{$premission->name}}">
                        <label class="form-check-label" for="inlineCheckbox1">{{$premission->name}}</label>
                      </div>
                    @endforeach
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-12">
                    <div class="text-center">
                        @csrf
                        <a href="{{route('roles.index')}}" class="btn btn-outline-secondary w-10 mt-4 mb-5 px-3">Go Back</a>
                        <button type="submit" class="btn bg-gradient-info w-20 mt-4 mb-5">Submit</button>
                    </div>
                  </div>
                </div>
                {{-- <div class="row"> --}}
            </form>
          </div>
        </div>
      </div>
</div>

@endsection

resources/views/dashoard/roles/index.blade.php
@extends('layouts.main')

@section('title', 'Roles')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="float-sm-end pb-4">
            <a href="{{route('roles.create')}}"  class="btn btn-success">Add Roles <span class="btn-inner--icon"><i class="ni ni-plus-61"></i></span></a>
        </div>
        <div class="clearfix"></div>
        <div class="card mb-4">
          <div class="card-header pb-0">
            <h6>Roles</h6>
          </div>
          <div class="card-body px-0 pt-0 pb-2">

            @livewire('dashboards.roles')

          </div>
        </div>
      </div>
</div>
@endsection