routes/web.php
<?php

use App\Http\Controllers\Admin\AddPermissionsController;
use App\Http\Controllers\Admin\AddPlasmaDonerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('pages.dashboard');
});

Auth::routes(['verify' => true]);

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'Admin\DashboardController@index')->name('home');

//Plasma
Route::get('plasma-verify/{plasma}', 'Admin\AddPlasmaDonerController@verify')->name('plasma.verify');
Route::resource('plasma', 'Admin\AddPlasmaDonerController');

Route::get('blood-verify/{bloodDonar}', 'Admin\AddBloodController@verify')->name('blood.verify');
Route::resource('blood', 'Admin\AddBloodController');

Route::get('ambulance-services-verify/{ambulance_service}', 'Admin\AddAmbulanceServicesController@verify')->name('ambulance-services.verify');
Route::resource('ambulance-services', 'Admin\AddAmbulanceServicesController');

//Har Oxygen
Route::get('oxygen-verify/{oxygen}', 'Admin\AddOxygenController@verify')->name('oxygen.verify');
Route::resource('oxygen', 'Admin\AddOxygenController');

Route::middleware(['auth','role:super-admin'])->group(function () {
    Route::resource('permissions', 'Admin\AddPermissionsController');
    Route::resource('roles', 'Admin\AddRolesController');
});

Route::middleware(['auth'])->group(function () {
    Route::get('profile', 'Admin\UserController@profile')->name('profile');
    Route::get('edit-profile', 'Admin\UserController@editProfile')->name('edit.profile');
    Route::post('edit-profile', 'Admin\UserController@update')->name('update.profile');
});

// Requests
Route::resource('requests', 'Admin\RequestsController');

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('pages.dashboard');
    }
}

app/Http/Livewire/Dashboards/AmbulanceServices.php
<?php

namespace App\Http\Livewire\Dashboards;

use Livewire\Component;
use App\AbmulaceServices;
use Livewire\WithPagination;
use Maklad\Permission\Models\Permission;

class AmbulanceServices extends Component
{
    use WithPagination;

    public $month = '';
    protected $sales;
    public $perPage = 10;
    public $sortField;
    public $sortAsc = false;
    public $search = null;


    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $search = $this->search;
        $sortField = $this->sortField?$this->sortField:'id';
        return view('livewire.dashboards.ambulance-services', [
            'ambulance_services' => AbmulaceServices::with('serviceTypes')->when($search, function ($query) use ($search) {
                return $query->where(function ($query2) use ($search) {
                        $query2->where('first_name', 'LIKE', "%$search%")
                            ->orWhere('last_name', 'LIKE', "%$search%")
                            ->orWhere('email', 'LIKE', "%$search%")
                            ->orWhere('service_name', 'LIKE', "%$search%")
                            ->orWhere('state', 'LIKE', "%$search%")
                            ->orWhere('district', 'LIKE', "%$search%")
                            ->orWhere('city', 'LIKE', "%$search%")
                            ->orWhere('mobile', 'LIKE', "%$search%")
                            ->orWhere('availabilty', 'LIKE', "%$search%")
                            // ->orWhere('available_units', 'LIKE', "%$search%")
                            ->orWhere('status', 'LIKE', "%$search%")
                            ->orWhere('created_at', 'LIKE', "%$search%");
                });
            })
            ->orderBy($sortField, $this->sortAsc ? 'asc' : 'desc')
            ->paginate(10),
        ]);
    }

}

app/Http/Livewire/Dashboards/BloodDonarsComponent.php
<?php

namespace App\Http\Livewire\Dashboards;

use App\BloodDonars;
use Livewire\Component;
use Livewire\WithPagination;

class BloodDonarsComponent extends Component
{
    use WithPagination;

    public $month = '';
    protected $sales;
    public $perPage = 10;
    public $sortField;
    public $sortAsc = false;
    public $search = null;

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $search = $this->search;
        $sortField = $this->sortField?$this->sortField:'id';
        return view('livewire.dashboards.blood-donars-component', [
            'blood_donars' => BloodDonars::when($search, function ($query) use ($search) {
                return $query->where(function ($query2) use ($search) {
                        $query2->where('fitst_name', 'LIKE', "%$search%")
                            ->orWhere('last_name', 'LIKE', "%$search%")
                            ->orWhere('email', 'LIKE', "%$search%")
                            ->orWhere('blood_group', 'LIKE', "%$search%")
                            ->orWhere('created_at', 'LIKE', "%$search%");
                });
            })
            ->orderBy($sortField, $this->sortAsc ? 'asc' : 'desc')
            ->paginate(10),
        ]);
    }
}

app/Http/Livewire/Dashboards/OxygenDonars.php
<?php

namespace App\Http\Livewire\Dashboards;

use App\Oxygen;
use App\PlasmaDonars;
use Livewire\Component;
use Livewire\WithPagination;

class OxygenDonars extends Component
{
    use WithPagination;

    public $month = '';
    protected $sales;
    public $perPage = 10;
    public $sortField;
    public $sortAsc = false;
    public $search = null;


    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $search = $this->search;
        $sortField = $this->sortField?$this->sortField:'id';
        return view('livewire.dashboards.oxygen-donars', [
            'oxygen_suppliers' => Oxygen::when($search, function ($query) use ($search) {
                return $query->where(function ($query2) use ($search) {
                        $query2->where('first_name', 'LIKE', "%$search%")
                            ->orWhere('last_name', 'LIKE', "%$search%")
                            ->orWhere('email', 'LIKE', "%$search%")
                            ->orWhere('company_name', 'LIKE', "%$search%")
                            ->orWhere('state', 'LIKE', "%$search%")
                            ->orWhere('district', 'LIKE', "%$search%")
                            ->orWhere('city', 'LIKE', "%$search%")
                            ->orWhere('mobile', 'LIKE', "%$search%")
                            ->orWhere('availabilty', 'LIKE', "%$search%")
                            ->orWhere('available_units', 'LIKE', "%$search%")
                            ->orWhere('status', 'LIKE', "%$search%")
                            ->orWhere('created_at', 'LIKE', "%$search%");
                });
            })
            ->orderBy($sortField, $this->sortAsc ? 'asc' : 'desc')
            ->paginate(10),
        ]);
    }

}

app/Http/Livewire/Dashboards/Permissions.php
<?php

namespace App\Http\Livewire\Dashboards;

use Livewire\Component;
use Livewire\WithPagination;
use Maklad\Permission\Models\Permission;

class Permissions extends Component
{
    use WithPagination;

    public $month = '';
    protected $sales;
    public $perPage = 10;
    public $sortField;
    public $sortAsc = false;
    public $search = null;

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $search = $this->search;
        $sortField = $this->sortField?$this->sortField:'id';
        return view('livewire.dashboards.permissions', [
            'permissions' => Permission::when($search, function ($query) use ($search) {
                return $query->where(function ($query2) use ($search) {
                        $query2->where('name', 'LIKE', "%$search%")
                            ->orWhere('guard_name', 'LIKE', "%$search%");
                });
            })
            ->orderBy($sortField, $this->sortAsc ? 'asc' : 'desc')
            ->paginate(10),
        ]);
    }


}

app/Http/Livewire/Dashboards/PlasmaDoanars.php
<?php

namespace App\Http\Livewire\Dashboards;

use App\PlasmaDonars;
use Livewire\Component;
use Livewire\WithPagination;

class PlasmaDoanars extends Component
{
    use WithPagination;

    public $month = '';
    protected $sales;
    public $perPage = 10;
    public $sortField;
    public $sortAsc = false;
    public $search = null;

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $search = $this->search;
        $sortField = $this->sortField?$this->sortField:'id';
        return view('livewire.dashboards.plasma-doanars', [
            'plasma_donars' => PlasmaDonars::when($search, function ($query) use ($search) {
                return $query->where(function ($query2) use ($search) {
                        $query2->where('first_name', 'LIKE', "%$search%")
                            ->orWhere('last_name', 'LIKE', "%$search%")
                            ->orWhere('email', 'LIKE', "%$search%")
                            ->orWhere('blood_group', 'LIKE', "%$search%")
                            ->orWhere('created_at', 'LIKE', "%$search%");
                });
            })
            ->orderBy($sortField, $this->sortAsc ? 'asc' : 'desc')
            ->paginate(10),
        ]);
    }

}

app/Http/Livewire/Dashboards/Roles.php
<?php

namespace App\Http\Livewire\Dashboards;

use Livewire\Component;
use Livewire\WithPagination;
use Maklad\Permission\Models\Role;

class Roles extends Component
{
    use WithPagination;

    public $month = '';
    protected $sales;
    public $perPage = 10;
    public $sortField;
    public $sortAsc = false;
    public $search = null;

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $search = $this->search;
        $sortField = $this->sortField?$this->sortField:'id';
        return view('livewire.dashboards.roles', [
            'roles' => Role::when($search, function ($query) use ($search) {
                return $query->where(function ($query2) use ($search) {
                        $query2->where('name', 'LIKE', "%$search%")
                            ->orWhere('guard_name', 'LIKE', "%$search%");
                });
            })
            ->orderBy($sortField, $this->sortAsc ? 'asc' : 'desc')
            ->paginate(10),
        ]);
    }

    // public function render()
    // {
    //     return view('livewire.dashboards.roles');
    // }
}

app/Http/Livewire/Dashboards/ShowFormRequests.php
<?php

namespace App\Http\Livewire\Dashboards;

use App\Request as FormRequest;
use Livewire\Component;
use Livewire\WithPagination;

class ShowFormRequests extends Component
{
    use WithPagination;

    public $month = '';
    protected $sales;
    public $perPage = 10;
    public $sortField;
    public $sortAsc = false;
    public $search = null;


    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortAsc = ! $this->sortAsc;
        } else {
            $this->sortAsc = true;
        }

        $this->sortField = $field;
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        $search = $this->search;
        $sortField = $this->sortField?$this->sortField:'id';
        return view('livewire.dashboards.show-form-requests', [
            'request_forms' => FormRequest::when($search, function ($query) use ($search) {
                return $query->where(function ($query2) use ($search) {
                        $query2->where('fitst_name', 'LIKE', "%$search%")
                            ->orWhere('last_name', 'LIKE', "%$search%")
                            ->orWhere('email', 'LIKE', "%$search%")
                            ->orWhere('state', 'LIKE', "%$search%")
                            ->orWhere('district', 'LIKE', "%$search%")
                            ->orWhere('city', 'LIKE', "%$search%")
                            ->orWhere('state', 'LIKE', "%$search%")
                            ->orWhere('pincode', 'LIKE', "%$search%")
                            ->orWhere('requests', 'LIKE', "%$search%")
                            ->orWhere('created_at', 'LIKE', "%$search%");
                });
            })
            ->orderBy($sortField, $this->sortAsc ? 'asc' : 'desc')
            ->paginate(10),
        ]);
    }

}

resources/views/livewire/dashboards/ambulance-services.blade.php
<div>
    {{-- The Master doesn't talk, he acts. --}}

    <div class="col-xl-3 col-lg-6 col-md-6 mb-1 px-3">
        <input wire:model="search" class="form-control" type="text" placeholder="Search ...">
        {{-- <a href="{{route('admin.day.sales.export',['month'=>$])}}" class="btn btn-info">Export</a> --}}
    </div>
    <div class="table-responsive p-0">
        <table class="table align-items-center mb-0">
          <thead>
            <tr>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                <a wire:click.prevent="sortBy('first_name')" role="button" href="#">Supplier
                @include('includes._sort-icon', ['field' => 'first_name'])</a> </th>
              </th>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                  <a wire:click.prevent="sortBy('company_name')" role="button" href="#">Company name
                @include('includes._sort-icon', ['field' => 'service_name'])</a></th>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                  <a wire:click.prevent="sortBy('availabilty')" role="button" href="#">Availabilty
                @include('includes._sort-icon', ['field' => 'availabilty'])</a></th>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                  <a wire:click.prevent="sortBy('available_units')" role="button" href="#">Availabe Units
                @include('includes._sort-icon', ['field' => 'available_units'])</a></th>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                  <a wire:click.prevent="sortBy('state')" role="button" href="#">State
                @include('includes._sort-icon', ['field' => 'state'])</a></th>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                  <a wire:click.prevent="sortBy('district')" role="button" href="#">District
                @include('includes._sort-icon', ['field' => 'district'])</a></th>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                  <a wire:click.prevent="sortBy('city')" role="button" href="#">city
                @include('includes._sort-icon', ['field' => 'city'])</a></th>
              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                  <a wire:click.prevent="sortBy('status')" role="button" href="#">Status
                @include('includes._sort-icon', ['field' => 'status'])</a></th>
              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                <a wire:click.prevent="sortBy('created_at')" role="button" href="#">Created At
                    @include('includes._sort-icon', ['field' => 'created_at'])
                </a>
              </th>
              <th class="text-secondary opacity-7">Action</th>
            </tr>
          </thead>
          <tbody>

              @foreach ($ambulance_services as $ambulance)
            <tr>
                <td>
                  <div class="d-flex px-2 py-1">
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="mb-0 text-sm">{{$ambulance->first_name.' '.$ambulance->last_name}}</h6>
                      <p class="text-xs text-secondary mb-0">{{$ambulance->email}}</p>
                      <p class="text-xs text-secondary mb-0">{{$ambulance->mobile}}</p>
                    </div>
                  </div>
                </td>
                <td>
                  <p class="text-xs font-weight-bold mb-0">{{$ambulance->service_name}}</p>
                </td>
                <td>
                  <p class="text-xs font-weight-bold mb-0">{{$ambulance->availability}}</p>
                </td>
                <td>
                  <p class="text-xs font-weight-bold mb-0"> {{$ambulance->serviceTypes->implode('type', ', ')}}</p>
                </td>
                <td>
                  <p class="text-xs font-weight-bold mb-0">{{$ambulance->state}}</p>
                </td>
                <td>
                  <p class="text-xs font-weight-bold mb-0">{{$ambulance->district}}</p>
                </td>
                <td>
                  <p class="text-xs font-weight-bold mb-0">{{$ambulance->city}}</p>
                </td>
                <td class="align-middle text-center text-sm">
                  <span class="badge badge-sm bg-gradient-success">{{$ambulance->status}}</span>
                </td>
                <td class="align-middle text-center">
                  <span class="text-secondary text-xs font-weight-bold">{{$ambulance->created_at}}</span>
                </td>
                <td class="align-middle">
                    @can('edit ambulance')
                    <a href="{{route('ambulance-services.edit',$ambulance->id)}}" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="Edit">
                      <i class="fas fa-edit"></i>
                    </a>
                    @endcan
                    @can('edit ambulance')
                    <a data-bs-toggle="modal" data-bs-target="#modal-notification" class="trigger-btn" data-toggle="modal" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="Delete">
                      <i class="fas fa-trash-alt"></i>
                    </a>
                    @endcan
                    @can('show ambulance')
                    <a href="{{route('ambulance-services.show',$ambulance->id)}}" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="view">
                      <i class="fas fa-table"></i>
                    </a>
                    @endcan
                    @can('verify ambulance')
                    <a href="{{route('ambulance-services.verify',$ambulance->id,$_GET)}}" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="Edit user">
                      <i class="fas fa-check-square"></i>
                    </a>
                    @endcan
                </td>
              </tr>
            @endforeach

          </tbody>
        </table>

        {{ $ambulance_services->links() }}

      </div>


      @include('includes.delete-modal', ['variableName' => []])


</div>

resources/views/livewire/dashboards/blood-donars-component.blade.php
<div>
    {{-- The Master doesn't talk, he acts. --}}

    <div class="col-xl-3 col-lg-6 col-md-6 mb-1 px-3">
        <input wire:model="search" class="form-control" type="text" placeholder="Search ...">
        {{-- <a href="{{route('admin.day.sales.export',['month'=>$])}}" class="btn btn-info">Export</a> --}}
    </div>
    <div class="table-responsive p-0">
        <table class="table align-items-center mb-0">
          <thead>
            <tr>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                <a wire:click.prevent="sortBy('first_name')" role="button" href="#">Donar
                @include('includes._sort-icon', ['field' => 'first_name'])</a> </th>
              </th>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                  <a wire:click.prevent="sortBy('blood_group')" role="button" href="#">Blood Group
                @include('includes._sort-icon', ['field' => 'blood_group'])</a></th>
              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                  <a wire:click.prevent="sortBy('status')" role="button" href="#">Status
                @include('includes._sort-icon', ['field' => 'status'])</a></th>
              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                <a wire:click.prevent="sortBy('created_at')" role="button" href="#">Created At
                    @include('includes._sort-icon', ['field' => 'created_at'])
                </a>
              </th>
              <th class="text-secondary opacity-7">Action</th>
            </tr>
          </thead>
          <tbody>

              {{-- {{dd($blood_donar_donars)}} --}}
            @foreach ($blood_donars as $blood_donar)
            <tr>
                <td>
                  <div class="d-flex px-2 py-1">
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="mb-0 text-sm">{{$blood_donar->first_name.' '.$blood_donar->last_name}}</h6>
                      <p class="text-xs text-secondary mb-0">{{$blood_donar->email}}</p>
                    </div>
                  </div>
                </td>
                <td>
                  <p class="text-xs font-weight-bold mb-0">{{$blood_donar->blood_group}}</p>
                  {{-- <p class="text-xs text-secondary mb-0">Organization</p> --}}
                </td>
                <td class="align-middle text-center text-sm">
                  <span class="badge badge-sm bg-gradient-success">{{$blood_donar->status}}</span>
                </td>
                <td class="align-middle text-center">
                  <span class="text-secondary text-xs font-weight-bold">{{$blood_donar->created_at}}</span>
                </td>
                <td class="align-middle">
                    @can('edit blood')
                    <a href="{{route('blood.edit',$blood_donar->id)}}" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="Edit">
                      <i class="fas fa-edit"></i>
                    </a>
                    @endcan
                    @can('edit blood')
                    <a data-bs-toggle="modal" data-bs-target="#modal-notification" class="trigger-btn" data-toggle="modal" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="Delete">
                      <i class="fas fa-trash-alt"></i>
                    </a>
                    @endcan
                    @can('show blood')
                    <a href="{{route('blood.show',$blood_donar->id)}}" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="view">
                      <i class="fas fa-table"></i>
                    </a>
                    @endcan
                    @can('verify blood')
                    <a href="{{route('blood.verify',$blood_donar->id,$_GET)}}" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="Edit user">
                        <i class="fas fa-check-square"></i>
                    </a>
                    @endcan
                </td>
              </tr>
            @endforeach

          </tbody>
        </table>

        {{ $blood_donars->links() }}

      </div>


      @include('includes.delete-modal', ['variableName' => []])


</div>

resources/views/livewire/dashboards/permissions.blade.php
<div>
    {{-- The Master doesn't talk, he acts. --}}

    <div class="col-xl-3 col-lg-6 col-md-6 mb-1 px-3">
        <input wire:model="search" class="form-control" type="text" placeholder="Search ...">
        {{-- <a href="{{route('admin.day.sales.export',['month'=>$])}}" class="btn btn-info">Export</a> --}}
    </div>
    <div class="table-responsive p-0">
        <table class="table align-items-center mb-0">
          <thead>
            <tr>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                <a wire:click.prevent="sortBy('name')" role="button" href="#">Name
                @include('includes._sort-icon', ['field' => 'name'])</a> </th>
              </th>
              <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                  <a wire:click.prevent="sortBy('guard_name')" role="button" href="#">Guard
                @include('includes._sort-icon', ['field' => 'guard_name'])</a></th>
              <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                <a wire:click.prevent="sortBy('created_at')" role="button" href="#">Created At
                    @include('includes._sort-icon', ['field' => 'created_at'])
                </a>
              </th>
              <th class="text-secondary opacity-7">Action</th>
            </tr>
          </thead>
          <tbody>

              {{-- {{dd($permission_donars)}} --}}
            @foreach ($permissions as $permission)
            <tr>
                <td>
                  <div class="d-flex px-2 py-1">
                    <div class="d-flex flex-column justify-content-center">
                      {{-- <h6 class="mb-0 text-sm">{{$permission->name}}</h6> --}}
                      <p class="text-xs text-secondary mb-0">{{$permission->name}}</p>
                    </div>
                  </div>
                </td>
                <td>
                  <p class="text-xs font-weight-bold mb-0">{{$permission->guard_name}}</p>
                  {{-- <p class="text-xs text-secondary mb-0">Organization</p> --}}
                </td>
                {{-- <td class="align-middle text-center text-sm">
                  <span class="badge badge-sm bg-gradient-success">{{$permission->status}}</span>
                </td> --}}
                <td class="align-middle text-center">
                  <span class="text-secondary text-xs font-weight-bold">{{$permission->created_at}}</span>
                </td>
                <td class="align-middle">
                  <a href="{{route('permissions.edit',$permission->id)}}" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="Edit">
                    <i class="fas fa-edit"></i>
                  </a>
                  <a data-bs-toggle="modal" data-bs-target="#modal-notification" class="trigger-btn" data-toggle="modal" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="Delete">
                    <i class="fas fa-trash-alt"></i>
                  </a>
                  {{-- <a href="{{route('permissions.show',$permission->id)}}" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="view">
                    <i class="fas fa-table"></i>
                  </a>
                  <a href="{{route('plasma.verify',$permission->id,$_GET)}}" class="text-secondary font-weight-bold" data-toggle="tooltip" data-original-title="Edit user">
                    <i class="fas fa-check-square"></i> --}}
                  </a>
                </td>
              </tr>
            @endforeach

          </tbody>
        </table>

        {{ $permissions->links() }}

      </div>


      @include('includes.delete-modal', ['variableName' => []])


</div>